name: neclab_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyometiff
  - matplotlib
  - scikit-learn
  - libvorbis
  - opencv
  - pandas
  - pillow
  - numpy
  - scikit-image
  - scipy
  - openpyxl
  - xlrd
